spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']  #todo Укажите адрес и порт вашего приложения